{
 "title": "Prometheus 2.0 Stats",
 "tags": [ "prometheus" ],
 "time": { "from": "2024-04-12T18:23:22.215Z", "to": "2024-04-12T19:04:29.688Z" },
 "panels": [
  {
   "title": "Head Chunks",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "channel": "plugin/testdata/random-2s-stream"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Profile",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "title": "WAL Corruptions",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Samples Appended",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Blocks Loaded",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Head Block GC Activity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active Appenders",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "targets": [
    { "panelId": 16 }
   ]
  },
  {
   "title": "Rule Group Eval Duration",
   "type": "geomap",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rule Group Eval Activity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Compaction Activity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(prometheus_tsdb_compaction_duration_bucket{job=\"prometheus\"}[5m])) by (le))",
     "legendFormat": "duration-{{p99}}"
    },
    {
     "expr": "irate(prometheus_tsdb_compactions_total{job=\"prometheus\"}[5m])",
     "legendFormat": "compactions"
    },
    {
     "expr": "irate(prometheus_tsdb_compactions_failed_total{job=\"prometheus\"}[5m])",
     "legendFormat": "failed"
    },
    {
     "expr": "irate(prometheus_tsdb_compactions_triggered_total{job=\"prometheus\"}[5m])",
     "legendFormat": "triggered"
    }
   ]
  },
  {
   "title": "Reload Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_reloads_total{job=\"prometheus\"}[5m])",
     "legendFormat": "reloads"
    },
    {
     "expr": "rate(prometheus_tsdb_reloads_failures_total{job=\"prometheus\"}[5m])",
     "legendFormat": "failures"
    }
   ]
  },
  {
   "title": "Query Durations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_engine_query_duration_seconds{job=\"prometheus\", quantile=\"0.99\"}",
     "legendFormat": "{{slice}}_p99"
    }
   ]
  }
 ]
}